version: "3"
services:
  docker-mysqldb:
    image: mysql:8
    ports:
      - '3306:3306'
    networks:
      - springboot-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=db
  imshare-back:
    build:
      context: .
      dockerfile_inline: |
        FROM openjdk:17
        COPY ./back/target/*.jar ./app.jar
        CMD ["java","-jar","app.jar"]
    volumes:
      - shared-volume:/images
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysqldb:3306/db
    networks:
      - springboot-mysql
    depends_on:
      - docker-mysqldb
  imshare-front:
    build:
      context: .
      dockerfile_inline: |
        FROM nginx
        RUN mkdir -p ./src
        COPY ./front/dist/front /src
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - shared-volume:/images
    ports:
      - "80:8081"
networks:
  springboot-mysql: 
volumes:
  shared-volume: